version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - ${DB_PORT}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      # copy the create_tables.sql file to create table
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
    command: -p ${DB_PORT}
  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    expose:
      - ${API_PORT}
    volumes:
      - /app/node_modules
  front_build:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./front/dist:/app/dist
      - /app/node_modules
      - ./reverse_proxy.conf:/etc/nginx/conf.d/default.conf


